### ISSUE TITLE
Bucketlike items with higher capacity than world-interactable placed liquid containers can duplicate liquid when used on full container

### ISSUE THREAD

**Issue by Barhandar** [anegostudios/VintageStory-Issues#2089]
**Game Version:** 1.16.5
**Platform:** Windows  
**Modded:** Yes (requires conditions not yet present in stock game to manifest)
**SP/MP:** Either

### Description
When taking liquid with right-click out of a full bucket (10L) or a barrel (50L) with a handheld liquid container with larger capacity (Expanded Foods cauldrons with 20/50L, a modified-for-testing-this jug with 300L) that _already has some liquid in it_, the handheld item gets filled completely instead of the amount being added.  
The placed item is emptied as expected. Shift- and Ctrl-clicking works correctly(ish).  Using empty item on a full one works correctly (e.g. empty cauldron on full 10L bucket results in 10L in the cauldron). Using partially-filled item on partially-filled one works correctly. Using handhelds with identical or lower capacity works correctly. 

### How to reproduce
Have an item that can be used for liquid transfer while being held in inventory, such as a bucket, a jug or Expanded Foods cauldron, with capacity higher than a world-interactable liquid container, such as a bucket or a barrel. Have the placed item full. Have some of the same liquid in the held item. Right-click the placed item with the held item. Observe the held item becoming full despite larger capacity.

### Expected behavior
The handheld item having the accurate combined amount of liquid.

**Comment by Craluminum2413** [comment]
Can you try to reproduce that in 1.17.0-rc.3? Some [liquid dupe bug with barrels](https://info.vintagestory.at/v1dot17#:~:text=Fixed%3A%20Liquid%20dupe%20bug%20with%20barrels) was fixed in 1.17 pre=releases

**Comment by Barhandar** [comment]
It's not specific to barrels. Confirming this bug is reproducible in 1.17.0-pre.5, which is listed as the latest version.

**Comment by Craluminum2413** [comment]
The latest version is 1.17.0-rc.3

**Comment by Barhandar** [comment]
My apologies, it is downloaded elsewhere and so I've missed it. Nonetheless, the issue is still present on that version as well.

**Comment by Craluminum2413** [comment]
It would be better to have direct reproduce steps instead just a lot of text, for example:
1. Place a barrel
2. Break a block under the barrel
3. It fell and didn't break

**Comment by Barhandar** [comment]
These are the direct reproduce steps, but I can put them in an expanded list form (though not edit the issue body because github is dumb).

1. Adjust the jug's capacity to more than 10L (for purposes of clarity, higher is better - I suggest 300L) in `assets\survival\blocktypes\clay\jug.json`, `capacityLitres` entry, so that you have a larger-than-usual container that triggers the issue.
    * Can also use mods that already provide such a container, such as a Cauldron (50L) from Expanded Foods.
2. Ingame, spawn in two water buckets and the jug.
    * Also works with all other liquids.
3. Place the buckets.
4. Right-click on one of the buckets with the jug.
5. The jug will have the correct amount of 10L of water in it, and the bucket will have 0L.
    * You can also shift-right-click, as the exact amount of liquid in the jug does not matter, only that it is not empty.
6. Right-click on the other, full bucket with the jug.
7. The jug will have incorrect amount of `capacityLitres` of water in it, even though it should have 20L, and the bucket will have 0L.
8. The steps 6-7 can be done with a full barrel and a jug that fits more than 50L, for the same result - empty barrel and a jug that is filled to capacity, no matter how high it is.
