### ISSUE TITLE
Last piece of pie has no nutrition

### ISSUE THREAD

**Issue by cristian-t** [anegostudios/VintageStory-Issues#2117]
**Game Version:** 1.17.0-rc.5
**Platform:** Windows
**Modded:** No
**SP/MP:** Singleplayer

### Description
Eating the last piece of a pie does not affect nutrition.
In my case, it was a pie made with spelt flour and filled with onions, in case it matters.
The world was created in 1.17.0-rc.3

### How to reproduce
1. Make a (spelt onion) pie
2. Slice and eat the first 3 pieces and get nutrition
3. Pick up and eat the last remaining piece

### Expected behavior
You should get the piece's nutrition

**Comment by Cataclysmanic** [comment]
I had the same bug, and in case it helps at all, here are a few images, and a few pieces of information.

It happens with any type of pie with any ingredient, and you have to pick up the last piece without a knife in hand.
The amount of nutrition from the last piece (if you pick it up without the knife) comes as a full serving instead of as a quarter of a serving, and it doesn't give any nutrition when eaten.

![2022-10-13_21-04-48](https://user-images.githubusercontent.com/74816566/195746146-a6706ea2-326d-47bb-9eac-d1144d5ade90.png)
![2022-10-13_21-04-42](https://user-images.githubusercontent.com/74816566/195746150-93b55332-6517-4e6f-add2-02e0c602bdb5.png)
![2022-10-13_21-04-44](https://user-images.githubusercontent.com/74816566/195746153-9144515d-5821-49b8-bfc7-787473fb8b40.png)

**Comment by noelle-lavenza** [comment]
I explicitly stated that #2316 was ***not*** a duplicate of this issue. This issue still exists. Please reopen it.

**Comment by Craluminum2413** [comment]
@noelle-lavenza But it was fixed?

**Comment by noelle-lavenza** [comment]
Here's a video demonstrating it, from the #bug-reports channel on the Discord.
[unknown_replay_2023.04.26-15.11.webm](https://user-images.githubusercontent.com/101909198/234588300-787eaf4a-6134-42a8-8b71-22599b87ca24.webm)

**Comment by duck-rh** [comment]
Quack,

I'm using 1.18.5 and I've been "eating" this problem many times now. At first I thought I made a mistake, then maybe a bug similar to #2755, but indeed I did take the piece without the knife. I just tested and using the knife seem to work indeed, but the satiety seemed low so I'll try to make more tests.

Anyway, sorry for the lack of proper details but just to say the bug is not fixed.
\\_o<

**Comment by Zorm** [comment]
Small update to this bug: It does not happen when eating charred pie.

**Comment by pizza2004** [comment]
Fixed in rc.6.
