### ISSUE TITLE
Water physics

### ISSUE THREAD

**Issue by Maisa85** [anegostudios/VintageStory-Issues#823]
Is there a reason why water does not fill holes properly underwater when blocks are removed? Also trying to get "bubbly water" back to "stable" with water buckets is beyond my comprehension. :D

**Comment by radfast** [comment]
Thanks for reporting, sorry for slow response.  This issue should be fixed - or definitely improved :) - in game version `1.15-rc1` which is now available if you'd like to try it.

[Detail: it was fixed in `v1.15.0-pre.8`]

**Comment by JBraunsmaJr** [comment]
@copygirl @radfast, May I ask how you format the version tag for this?

In the tagged branch I'm particularly interested in the ".8" -- does this mean the next minor build of the game will be 1.15.8?

I still find this bug in 1.15.5.

**Comment by copygirl** [comment]
`1.15.0-pre.8` was a pre-release version that predates the official release of `1.15.0`, meaning the bug should have been fixed already. (`1.14.10` -> `1.15.0-pre.1` -> `1.15.0-pre.2` .... -> `1.15.0-rc.1` -> `1.15.0-rc.2` .... -> `1.15.0` -> `1.15.1`)

**Comment by copygirl** [comment]
I'm not sure what the fix / improvement was so I'll reopen this for now and let radfast respond.

**Comment by JBraunsmaJr** [comment]
Just in case, here are my findings

**Game Version:** 1.15.5 (stable)
**Platform:** Windows
**Modded:** No

### Description
I've been noticing a few water related bugs.

In some cases, a single water block with no adjacent neighbors on the same plane will not behave as expected. It just sits there as a water block.

While trying to reproduce this I stumbled across a separate scenario 

### How to reproduce
1. Place column of blocks in a body of water. 
2. Delete / remove the column you just made

If viewed from the side, picture a 3x4 grid

| Symbol | Meaning |
| - | - |
| x | empty tile / air |
| w | water tile |
| b | solid block |

Starting Scenario
| 1 |  2 | 3 |
| - | - | - |
|w|x|w|
|w|x|w|
|w|x|w|
|w|b|w|

When I add a block that is diagonally below an air block the air pocket fills up with water
| 1 |  2 | 3 |
| - | - | - |
|w|x|w|
|w|x|w|
|w|w|w|
|w|b|b|

Given the starting scenario again - if I put a block adjacent to the middle air block it corrects all 3 air pockets.
| 1 |  2 | 3 |
| - | - | - |
|w|w|w|
|w|w|b|
|w|w|w|
|w|b|w|

### Expected behavior
An empty tile surrounded by water should be filled with water

### Screenshots
![Issue](https://user-images.githubusercontent.com/28987352/133138543-895e97f2-c028-40de-a7d8-4d463cd04f44.png)
![BlockPlacement1](https://user-images.githubusercontent.com/28987352/133138546-db141123-ed83-42c6-93b5-fc7d94df1e50.PNG)
![BlockPlacement2](https://user-images.githubusercontent.com/28987352/133138540-44cd0a6e-3982-4a6c-b6b8-04257d51f36f.PNG)

**Comment by DArkHekRoMaNT** [comment]
Partially fixed, but still leaves flows (1.18.3)
![image](https://github.com/anegostudios/VintageStory-Issues/assets/15899143/f450015b-52b6-4aba-a131-1e21be14fb0f)
